### ISSUE TITLE
Consider developing around existing relations semantics

### ISSUE THREAD

**Issue by pbuttigieg** [tdwg/interaction#12]
To help coordinate any interaction semantics with existing, interoperable, and well-adopted ontologies, we should consider extending the  work that @cmungall and others have done in the [Relations Ontology](http://www.obofoundry.org/ontology/ro.html).

Responding to several requests from the ecology domain, RO has an "eco" subset which includes semantics for various interactions (see, for example, [this class](http://purl.obolibrary.org/obo/RO_0002434) and its subclasses).

Task groups can add material there (with microcrediting and shared governance on the table) to make sure our output can be reused quickly by all the other interconnected ontologies.

**Comment by zedomel** [comment]
Sounds good to me! @jhpoelen already has mentioned this resources on commit 430b534266437863278aaeadc31c62fa4b05c46e (line 38)
