### ISSUE TITLE
Wood decomposition data set as a focus for ontologising...

### ISSUE THREAD

**Issue by pbuttigieg** [tdwg/interaction#13]
@dschigel to send @pbuttigieg a data set to mine for key interaction terms as a motivating use case. Terms will head into ENVO/ECOCORE/RO for testing. Coordinate RO activity with @cmungall

**Comment by balbertini** [comment]
Can you upload it on github so others can also take a look?
Thx

**Comment by dschigel** [comment]
Am searching... apparently it's not with me here at TDWG. Will upload here,

**Comment by pbuttigieg** [comment]
Just a friendly reminder on this: best we start early, as things that seem straightforward can get quite involved.
