### ISSUE TITLE
Repository & team setup

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/interaction#14]
Summary of the move of this repository to GitHub:

1. I moved https://github.com/BioComp-USP/interaction-data-group to https://github.com/tdwg/interaction
2. I chose `interaction` as the shortname for the group (cf. [attribution](https://github.com/tdwg/attribution) or [annotations](https://github.com/tdwg/annotations)). That shortname will appear in the repo url, the team name and eventually in the TDWG website URL.
3. I created a TDWG team [interaction](https://github.com/orgs/tdwg/teams/interaction/members), which has **admin rights to this repository**. That team can be notified by using @tdwg/interaction. I invited @zedomel and @saraiva-usp (as maintainer). Please let me know if the maintainer should be someone else. The maintainer can add more people (they will get admin rights to the repo too), e.g. some of the [watchers](https://github.com/tdwg/interaction/watchers). Everyone who watched the old repo, will continue to do so (and get notifications).
4. I updated the README a bit in 5332644dc32a4a436c94fe9a18055a4791db01b3 (e.g. fixed the link to the issues), but it might need a more extensive rewrite now that the group has been adopted by TDWG.
5. The GitHub hosted website is now available at http://tdwg.github.io/interaction
6. Can you send me the charter of the group (preferrably as a Markdown document)?

**Comment by zedomel** [comment]
Thanks @peterdesmet. The charter is already linked to commit 7d85d58a0ff16ba0889d82d7d3b7cd56cbb3862f. 
I will make some changes in the charter to point to this repository.

**Comment by zedomel** [comment]
Dear @peterdesmet 
I have accepted your invitation to TDWG organisation on GitHub, but I'm still without write access to this repo. Could you add me as maintainer, please?

Thanks.

**Comment by peterdesmet** [comment]
Sorry, should now be fixed!
