### ISSUE TITLE
Follow-up TDWG 2017 Annual Meeting

### ISSUE THREAD

**Issue by jhpoelen** [tdwg/interaction#15]
Hey y'all:

Just wanted to express my excitement about our TDWG Species Interaction Data workshop in Oct 2017 by:

1. writing a little blog post about our get-together (https://www.globalbioticinteractions.org/2017/11/21/catalyzing-data-exchange/)
2. spending some time on a beautiful dead wood interaction dataset published in 2006 (see https://jukuri.luke.fi/handle/10024/513946). I hope others will follow.
3. registering for GLOBIS-B workshop in Bari, Italy Feb 2018 (see meeting notes https://docs.google.com/document/d/1uiGHTCDHCTQirzXZdhF-Us21dTP78LfatihMHKV0OtE/edit?usp=sharing ).
4. creating a prototype on how to collaboratively build an inventory of species interaction dataset (see https://github.com/globalbioticinteractions/species-interaction-dataset-inventory) . Can you add summaries for your datasets or datasets you know? Do you have another idea on how to build an inventory of datasets?

Curious to hear your thoughts, hope you are well and hoping we'll get a chance to meet again soon. 

thx,
-jorrit

**Comment by qgroom** [comment]
Hi Jorrit,
thanks for sharing! Though it is sad to read of the disappearance of
databases. I hear of this all the time and yet people still don't recognize
the importance of open data to preserve their own legacy on science.
I look forward to Bari and developing ideas and actions further.
Regards
Quentin



Dr. Quentin Groom
(Botany and Information Technology)

Botanic Garden Meise
Domein van Bouchout
B-1860 Meise
Belgium

ORCID: 0000-0002-0596-5376 <http://orcid.org/0000-0002-0596-5376>

Landline; +32 (0) 226 009 20 ext. 364
FAX:      +32 (0) 226 009 45

E-mail:     quentin.groom@plantentuinmeise.be
Skype name: qgroom
Website:    www.botanicgarden.be

**Comment by dschigel** [comment]
Hello all,  - I hope this is the right way to reach all in the interest group on interactions.

I will need to give a short talk on what was done on the interactions data worldwide, where, how and by whom, on 8 February in a rather specific fungal meeting in Uppsala http://www.nefom.dk/. What is of interest to us, is that Nordic mycologists aim to construct a trait database for fungi we study, and interactions are very important for fungi - think host plants, insect fungivory etc, so there will be more interactions data from NEFOM that could be potentially aggregated at the global level.  I would appreciate advice from the IG on how best to inform this community that i) the bicycle is already invented ii) it is important to separate the directly observed primary interaction data, from the interpreted or "known as" kind of data and iii) to give an overview of the existing systems and approaches. It would be particularly valuable if you could share 2-3 slides you might already have on your system - I will make sure to cite you in my talk. My e-mail is dschigel@gbif.org and I will start working on my slides in one week, on the 29th of January. Thanks in advance!

**Comment by jhpoelen** [comment]
Here's some links to previous presentation about GloBI - I hope you find this useful for your talk 

presented at TDWG 2017 - https://speakerdeck.com/jhpoelen592/global-biotic-interactions-a-catalyst# 

presented at Berkeley BIDS 2015 - https://www.slideshare.net/jhpoelen245/globi-berkeley-institute-for-data-science-feb-5-2015

presented at UAM, Mexico City 2013 - https://www.slideshare.net/jhpoelen245/glo-bi-statusunido23may2013

Also, you might find some useful graphics at https://www.globalbioticinteractions.org/blog with logos at https://github.com/globalbioticinteractions/logo .

Happy to provide soft copies by email if needed.

**Comment by jhpoelen** [comment]
and @dschigel here's a one slide / poster presented at TDWG 2016 that captures most of GloBI's approach - https://dx.doi.org/10.6084/m9.figshare.4495130.v1 .

**Comment by dschigel** [comment]
Hi @jhpoelen many thanks, most useful.
