### ISSUE TITLE
How to use resourceRelationship in RDF?

### ISSUE THREAD

**Issue by zedomel** [tdwg/interaction#16]
The DwC class resourceRelationship has been used to express species interaction as we can see in [Plinian Core](https://github.com/tdwg/PlinianCore/wiki/InteractionAtomizedClass). 

The DwC RDF Guide states that: 

> The non-RDF use of terms organized under the dwc:ResourceRelationship class depends on values for dwc:resourceID and dwc:relatedResourceID, terms which cannot be used in RDF for reasons discussed in Section 2.6

And the [tdwg/rdf/ResourceRelationship.md](https://github.com/tdwg/rdf/blob/721bc5fa283db4264d7bd5ebf399d588dfd802d9/ResourceRelationship.md) has a workaround but it says:

> Note: the approach suggested in this document is no longer recommended due to concerns expressed by task group members about use of the Open Annotations model in this way

So, how should we use resourceRelationship in RDF? 

Thanks.

**Comment by jhpoelen** [comment]
For related discussion about resource relationship see https://github.com/trias-project/uredinales-belgium-checklist/issues/8 and https://www.globalbioticinteractions.org/2018/08/16/models-in-fashion/#darwin-core-archive--uredinales-of-belgium-flavor .

**Comment by jhpoelen** [comment]
BTW - I'd be interested to incorporate data based on PlinianCore into GloBI and add some examples. Please let me know if there's anyone who's actively using the extension.
